export default {
  '332':'Acesso Soluções de Pagamento S.A.',
  '117':'ADVANCED CORRETORA DE CÂMBIO LTDA',
  '272':'AGK CORRETORA DE CAMBIO S.A.',
  '349':'AMAGGI S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO',
  '188':'ATIVA INVESTIMENTOS S.A. CORRETORA DE TÍTULOS, CÂMBIO E VALORES',
  '280':'Avista S.A. Crédito, Financiamento e Investimento',
  '080':'B&T CORRETORA DE CAMBIO LTDA.',
  '654':'Banco A.J.Renner S.A',
  '246':'Banco ABC Brasil S.A',
  '075':'Banco ABN AMRO S.A',
  '121':'Banco Agibank S.A',
  '025':'Banco Alfa S.A',
  '065':'Banco Andbank (Brasil) S.A',
  '213':'Banco Arbi S.A',
  '096':'Banco B3 S.A',
  '024':'Banco BANDEPE S.A',
  '330':'Banco Bari de Investimentos e Financiamentos S/',
  '318':'Banco BMG S.A',
  '752':'Banco BNP Paribas Brasil S.A',
  '107':'Banco BOCOM BBM S.A',
  '063':'Banco Bradescard S.A',
  '036':'Banco Bradesco BBI S.A.',
  '122':'Banco Bradesco BERJ S.A.',
  '394':'Banco Bradesco Financiamentos S.A.',
  '237':'BRADESCO',
  '218':'Banco BS2 S.A',
  '208':'Banco BTG Pactual S.A',
  '336':'Banco C6 S.A.',
  '473':'Banco Caixa Geral – Brasil S.A',
  '412':'Banco Capital S.A',
  '040':'Banco Cargill S.A',
  '739':'Banco Cetelem S.A',
  '233':'Banco Cifra S.A',
  '745':'Banco Citibank S.A',
  '241':'Banco Clássico S.A',
  '756':'Banco Cooperativo do Brasil S.A. – BANCOO',
  '748':'Banco Cooperativo Sicredi S.A',
  '222':'Banco Credit Agricole Brasil S.A',
  '505':'Banco Credit Suisse (Brasil) S.A',
  '069':'Banco Crefisa S.A',
  '266':'Banco Cédula S.A',
  '003':'Banco da Amazônia S.A',
  '083':'Banco da China Brasil S.A',
  '707':'Banco Daycoval S.A',
  '300':'Banco de La Nacion Argentin',
  '495':'Banco de La Provincia de Buenos Aire',
  '335':'Banco Digio S.A.',
  '001':'Banco do Brasil S.A',
  '047':'Banco do Estado de Sergipe S.A',
  '037':'Banco do Estado do Pará S.A',
  '041':'Banco do Estado do Rio Grande do Sul S.A',
  '004':'Banco do Nordeste do Brasil S.A',
  '265':'Banco Fator S.A',
  '224':'Banco Fibra S.A',
  '626':'Banco Ficsa S.A',
  '094':'Banco Finaxis S.A',
  '612':'Banco Guanabara S.A',
  '012':'Banco Inbursa S.A',
  '604':'Banco Industrial do Brasil S.A',
  '653':'Banco Indusval S.A',
  '077':'Banco Inter S.A',
  '249':'Banco Investcred Unibanco S.A.',
  '479':'Banco ItauBank S.',
  '184':'Banco Itaú BBA S.A',
  '029':'Banco Itaú Consignado S.A.',
  '376':'Banco J. P. Morgan S.A',
  '074':'Banco J. Safra S.A',
  '217':'Banco John Deere S.A',
  '076':'Banco KDB S.A',
  '757':'Banco KEB HANA do Brasil S.A',
  '600':'Banco Luso Brasileiro S.A',
  '389':'Banco Mercantil do Brasil S.A',
  '370':'Banco Mizuho do Brasil S.A',
  '746':'Banco Modal S.A',
  '066':'Banco Morgan Stanley S.A',
  '456':'Banco MUFG Brasil S.A',
  '243':'Banco Máxima S.A',
  '007':'Banco Nacional de Desenvolvimento Econômico e Social – BNDE',
  '169':'Banco Olé Bonsucesso Consignado S.A',
  '079':'Banco Original do Agronegócio S.A',
  '212':'Banco Original S.A',
  '712':'Banco Ourinvest S.A',
  '623':'Banco PAN S.A',
  '611':'Banco Paulista S.A',
  '643':'Banco Pine S.A',
  '747':'Banco Rabobank International Brasil S.A',
  '633':'Banco Rendimento S.A',
  '741':'Banco Ribeirão Preto S.A',
  '120':'Banco Rodobens S.A',
  '422':'Banco Safra S.A',
  '033':'Banco Santander (Brasil) S.A',
  '743':'Banco Semear S.A',
  '754':'Banco Sistema S.A',
  '630':'Banco Smartbank S.A.',
  '366':'Banco Société Générale Brasil S.A',
  '637':'Banco Sofisa S.A',
  '464':'Banco Sumitomo Mitsui Brasileiro S.A',
  '082':'Banco Topázio S.A',
  '018':'Banco Tricury S.A',
  '634':'Banco Triângulo S.A',
  '655':'Banco Votorantim S.A',
  '610':'Banco VR S.A',
  '119':'Banco Western Union do Brasil S.A',
  '124':'Banco Woori Bank do Brasil S.A',
  '348':'Banco XP S.A.',
  '081':'BancoSeguro S.A',
  '021':'BANESTES S.A. Banco do Estado do Espírito Sant',
  '755':'Bank of America Merrill Lynch Banco Múltiplo S.A',
  '268':'BARI COMPANHIA HIPOTECÁRIA',
  '250':'BCV – Banco de Crédito e Varejo S.A',
  '144':'BEXS Banco de Câmbio S.A',
  '253':'Bexs Corretora de Câmbio S/A',
  '134':'BGC LIQUIDEZ DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  '017':'BNY Mellon Banco S.A',
  '301':'BPP Instituição de Pagamento S.A.',
  '126':'BR Partners Banco de Investimento S.A',
  '070':'BRB – Banco de Brasília S.A',
  '092':'Brickell S.A. Crédito',
  '173':'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.',
  '142':'Broker Brasil Corretora de Câmbio Ltda.',
  '292':'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.',
  '104':'Caixa Econômica Federa',
  '309':'CAMBIONET CORRETORA DE CÂMBIO LTDA.',
  '288':'CAROL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',
  '130':'CARUANA S.A. – SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO',
  '159':'Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor',
  '114':'Central Cooperativa de Crédito no Estado do Espírito Santo – CECOOP',
  '091':'CENTRAL DE COOPERATIVAS DE ECONOMIA E CRÉDITO MÚTUO DO ESTADO DO RIO GRANDE DO S',
  '320':'China Construction Bank (Brasil) Banco Múltiplo S.A',
  '477':'Citibank N.A',
  '180':'CM CAPITAL MARKETS CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  '127':'Codepe Corretora de Valores e Câmbio S.A.',
  '163':'Commerzbank Brasil S.A. – Banco Múltipl',
  '133':'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS DE CRÉDITO E ECONOMIA FAMILIAR E',
  '136':'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS UNICRED LTDA. – UNICRED DO BRASI',
  '060':'Confidence Corretora de Câmbio S.A.',
  '097':'Cooperativa Central de Crédito Noroeste Brasileiro Ltda',
  '085':'Cooperativa Central de Crédito – AILO',
  '279':'COOPERATIVA DE CREDITO RURAL DE PRIMAVERA DO LESTE',
  '016':'COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SANTA CATARINA E RI',
  '281':'Cooperativa de Crédito Rural Coopavel',
  '322':'Cooperativa de Crédito Rural de Abelardo Luz – Sulcredi/Crediluz',
  '286':'COOPERATIVA DE CRÉDITO RURAL DE OURO SULCREDI/OURO',
  '273':'Cooperativa de Crédito Rural de São Miguel do Oeste – Sulcredi/São Miguel',
  '098':'Credialiança Cooperativa de Crédito Rural',
  '010':'CREDICOAMO CREDITO RURAL COOPERATIVA',
  '089':'CREDISAN COOPERATIVA DE CRÉDITO',
  '011':'CREDIT SUISSE HEDGING-GRIFFO CORRETORA DE VALORES S.A',
  '342':'Creditas Sociedade de Crédito Direto S.A.',
  '321':'CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LT',
  '289':'DECYSEO CORRETORA DE CAMBIO LTDA.',
  '487':'Deutsche Bank S.A. – Banco Alemã',
  '140':'Easynvest – Título Corretora de Valores SA',
  '149':'Facta Financeira S.A. – Crédito Financiamento e Investimento',
  '196':'FAIR CORRETORA DE CAMBIO S.A.',
  '343':'FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.',
  '331':'Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.',
  '285':'Frente Corretora de Câmbio Ltda.',
  '278':'Genial Investimentos Corretora de Valores Mobiliários S.A.',
  '364':'GERENCIANET PAGAMENTOS DO BRASIL LTDA',
  '138':'Get Money Corretora de Câmbio S.A.',
  '064':'Goldman Sachs do Brasil Banco Múltiplo S.A',
  '177':'Guide Investimentos S.A. Corretora de Valores',
  '146':'GUITTA CORRETORA DE CAMBIO LTDA.',
  '078':'Haitong Banco de Investimento do Brasil S.A',
  '062':'Hipercard Banco Múltiplo S.A',
  '189':'HS FINANCEIRA S/A CREDITO, FINANCIAMENTO E INVESTIMENTOS',
  '269':'HSBC Brasil S.A. – Banco de Investimento',
  '271':'IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',
  '157':'ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.',
  '132':'ICBC do Brasil Banco Múltiplo S.A',
  '492':'ING Bank N.V',
  '139':'Intesa Sanpaolo Brasil S.A. – Banco Múltipl',
  '652':'Itaú Unibanco Holding S.A',
  '341':'BANCO ITAU S.A.',
  '488':'JPMorgan Chase Bank',
  '399':'Kirton Bank S.A. – Banco Múltiplo',
  '293':'Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.',
  '105':'Lecca Crédito, Financiamento e Investimento S/A',
  '145':'LEVYCAM – CORRETORA DE CAMBIO E VALORES LTDA.',
  '113':'Magliano S.A. Corretora de Cambio e Valores Mobiliarios',
  '323':'MERCADOPAGO.COM REPRESENTACOES LTDA.',
  '274':'MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORT',
  '259':'MONEYCORP BANCO DE CÂMBIO S.A.',
  '128':'MS Bank S.A. Banco de Câmbi',
  '354':'NECTON INVESTIMENTOS S.A. CORRETORA DE VALORES MOBILIÁRIOS E COMMODITIES',
  '191':'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.',
  '753':'Novo Banco Continental S.A. – Banco Múltipl',
  '260':'Nu Pagamentos S.A.',
  '111':'OLIVEIRA TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIARIOS S.A.',
  '319':'OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  '613':'Omni Banco S.A',
  '290':'Pagseguro Internet S.A.',
  '254':'Paraná Banco S.A',
  '326':'PARATI – CREDITO, FINANCIAMENTO E INVESTIMENTO S.A.',
  '194':'PARMETAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  '174':'PERNAMBUCANAS FINANCIADORA S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO',
  '315':'PI Distribuidora de Títulos e Valores Mobiliários S.A.',
  '100':'Planner Corretora de Valores S.A.',
  '125':'Plural S.A. – Banco Múltipl',
  '108':'PORTOCRED S.A. – CREDITO, FINANCIAMENTO E INVESTIMENTO',
  '306':'PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',
  '093':'PÓLOCRED SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORT',
  '329':'QI Sociedade de Crédito Direto S.A.',
  '283':'RB CAPITAL INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LIMITADA',
  '101':'RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  '270':'Sagitur Corretora de Câmbio Ltda.',
  '751':'Scotiabank Brasil S.A. Banco Múltipl',
  '276':'Senff S.A. – Crédito, Financiamento e Investimento',
  '545':'SENSO CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A',
  '190':'SERVICOOP – COOPERATIVA DE CRÉDITO DOS SERVIDORES PÚBLICOS ESTADUAIS DO RIO GRAN',
  '183':'SOCRED S.A. – SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO P',
  '365':'SOLIDUS S.A. CORRETORA DE CAMBIO E VALORES MOBILIARIOS',
  '299':'SOROCRED CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.',
  '014':'State Street Brasil S.A. – Banco Comercia',
  '197':'Stone Pagamentos S.A.',
  '340':'Super Pagamentos e Administração de Meios Eletrônicos S.A.',
  '307':'Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.',
  '352':'TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',
  '095':'Travelex Banco de Câmbio S.A',
  '143':'Treviso Corretora de Câmbio S.A.',
  '131':'TULLETT PREBON BRASIL CORRETORA DE VALORES E CÂMBIO LTDA',
  '129':'UBS Brasil Banco de Investimento S.A',
  '015':'UBS Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',
  '099':'UNIPRIME CENTRAL – CENTRAL INTERESTADUAL DE COOPERATIVAS DE CREDITO LTDA.',
  '084':'Uniprime Norte do Paraná – Coop de Economia e Crédito Mútuo dos Médicos',
  '373':'UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.',
  '298':'Vip’s Corretora de Câmbio Ltda.',
  '296':'VISION S.A. CORRETORA DE CAMBIO',
  '367':'VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.',
  '310':'VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',
  '102':'XP INVESTIMENTOS CORRETORA DE CÂMBIO,TÍTULOS E VALORES MOBILIÁRIOS S/A',
  '325':'Órama Distribuidora de Títulos e Valores Mobiliários S.A.',
  '355':'ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A',
}
