export default {
  '1': 'ELETRÔNICA COM REGISTRO',
  '2': 'ELETRÔNICA COM REGISTRO (2)',
  '3': 'CAUCIONADA ELETRÔNICA',
  '4': 'COBRANÇA SEM REGISTRO',
  '5': 'RÁPIDA COM REGISTRO (BLOQUETE EMITIDO PELO CLIENTE)',
  '6': 'CAUCIONADA RAPIDA',
  '7': 'DESCONTADA ELETRÔNICA'
}
