export default {
  '108': 'DIRETA ELETRÔNICA EMISSÃO INTEGRAL – CARNÊ',
  '104': 'ESCRITURAL ELETRÔNICA – CARNÊ',
  '138': 'ESCRITURAL ELETRÔNICA – MENSAGEM COLORIDA',
  '112': 'ESCRITURAL ELETRÔNICA – SIMPLES',
  '173': 'SEM REGISTRO COM EMISSÃO E ENTREGA',
  '196': 'SEM REGISTRO COM EMISSÃO E ENTREGA – 15 POSIÇÕES',
  '103': 'SEM REGISTRO COM EMISSÃO E ENTREGA – CARNÊ',
  '147': 'ESCRITURAL ELETRÔNICA – DÓLAR'
}
