export default {
  '01': 'DUPLICATA MERCANTIL',
  '02': 'NOTA PROMISSÓRIA',
  '03': 'NOTA DE SEGURO',
  '04': 'MENSALIDADE ESCOLAR',
  '05': 'RECIBO',
  '06': 'CONTRATO',
  '07': 'COSSEGUROS',
  '08': 'DUPLICATA DE SERVIÇO',
  '09': 'LETRA DE CÂMBIO',
  '13': 'NOTA DE DÉBITOS',
  '15': 'DOCUMENTO DE DÍVIDA',
  '16': 'ENCARGOS CONDOMINIAIS',
  '17': 'CONTA DE PRESTAÇÃO DE SERVIÇOS',
  '99': 'DIVERSOS'
}
