import bancos from '../bancos.js'
import {tipo} from '../lib.js'
import categorias from './notas/categorias.js'
import situacoes from './notas/situacoes.js'
import status from './notas/status.js'
import cpmf from './notas/cpmf.js'

export default ({X, fixo, numero, texto, data, mapa}) => {
  fixo('34100000')
  fixo(' ', 9)
  fixo(tipo(X, 'cnpjcpf'), 1)
  numero(X, 'cnpjcpf', 14)
  fixo(' ', 15)
  texto(X, 'codigo', 5)
  numero(X, 'agencia', 6)
  numero(X, 'conta', 12)
  fixo(' ')
  numero(X, 'dac', 1)
  texto(X, 'nome', 30)
  fixo('BANCO ITAU S/A', 30)
  fixo(' ', 10)
  fixo('2')
  data(X, 'geracao', 14)
  numero(X, 'sequencia', 6)
  fixo('050')
  fixo('0', 5)
  fixo(' ', 69)
  fixo('\r\n')
  fixo('34100011E0440050 ')
  fixo(tipo(X, 'cnpjcpf'), 1)
  numero(X, 'cnpjcpf', 14)
  fixo(' ', 15)
  fixo(X.codigo, 5)
  fixo(X.agencia, 6, true)
  fixo(X.conta, 12, true)
  fixo(' ')
  fixo(X.dac, 1)
  fixo(X.nome, 30)
  fixo(' ', 40)
  data(X, 'data_inicial', 8)
  numero(X, 'valor_inicial', 18, 2, true)
  mapa(X, 'status_inicial', status)
  fixo('BRL')
  fixo(X.sequencia, 5, true)
  fixo(' ', 62)
  fixo('\r\n')
  X.registros.forEach((R, index) => {
    fixo('34100013')
    fixo(index + 1, 5, true)
    fixo('E')
    fixo(() =>
      R.situacao == 'Bloqueado' ? 2 :
      R.situacao == 'Vinculado' ? 5 : 1
    , 1)
    fixo(' ', 2)
    fixo(tipo(X, 'cnpjcpf'), 1)
    fixo(X.cnpjcpf, 14)
    fixo('0', 6)
    fixo(' ', 9)
    fixo(X.codigo, 5)
    fixo(X.agencia, 6, true)
    fixo(X.conta, 12, true)
    fixo(' ')
    fixo(X.dac, 1)
    fixo(X.nome, 30)
    fixo(' ', 6)
    mapa(R, 'situacao', situacoes)
    fixo(() => R.agencia == '' || !/^0*$/.test(R.conta) ? '' :
      R.agencia == '00000' ? '00' : '01'
    , 2)
    mapa(R, 'banco', bancos)
    texto(R, 'agencia', 5)
    texto(R, 'conta', 12)
    fixo(Object.keys(cpmf), 1)
    fixo(' ', 8)
    data(R, 'movimento', 8)
    R.ocorrencia = R.movimento
    numero(R, 'valor', 18, 2, true)
    mapa(R, 'categoria', categorias)
    numero(R, 'info', 4)
    texto(R, 'descricao', 25)
    fixo(' ', 33)
    texto(R, 'id', 6)
    fixo('\r\n')
  })
  fixo('34100015')
  fixo(' ', 9)
  fixo(tipo(X, 'cnpjcpf'), 1)
  numero(X, 'cnpjcpf', 14)
  fixo(' ', 15)
  fixo(X.codigo, 5)
  fixo(X.agencia, 6, true)
  fixo(X.conta, 12, true)
  fixo(' ')
  fixo(X.dac, 1)
  fixo(' ', 16)
  numero(X, 'bloqueado', 18, 2)
  numero(X, 'limite', 18, 2)
  numero(X, 'pendente', 18, 2)
  data(X, 'data_final', 8)
  numero(X, 'valor_final', 18, 2, true)
  mapa(X, 'status_final', status)
  fixo(X.registros.length + 2, 6, true)
  fixo(Math.round(100 * X.registros.reduce(
    (total, {valor}) => total + (valor < 0 ? -valor : 0)
  , 0)), 18, true)
  fixo(Math.round(100 * X.registros.reduce(
    (total, {valor}) => total + (valor > 0 ? valor : 0)
  , 0)), 18, true)
  fixo('0', 28)
  fixo('\r\n')
  fixo('34199999')
  fixo(' ', 9)
  fixo('000001')
  fixo(X.registros.length + 4, 6, true)
  fixo('000001')
  fixo(' ', 205)
  fixo('\r\n')
}
