export default {
  '01': 'Crédito em conta corrente',
  '02': 'Cheque pagamento/administrativo',
  '03': 'DOC C',
  '05': 'Crédito em conta poupança',
  '06': 'Crédito em conta corrente de mesma titularidade',
  '07': 'DOC D',
  '10': 'Ordem de pagamento à disposição',
  '11': 'Pagamento de contas e Tributos com código de barras',
  '13': 'Pagamento de concessionárias',
  '16': 'DARF normal',
  '17': 'GPS - guia da previdência social',
  '18': 'DARF simples',
  '19': 'IPTU/ISS/outros tributos municipais',
  '20': 'Caixa autenticação',
  '22': 'GARE – SP ICMS',
  '23': 'GARE SP DR',
  '24': 'GARE SP ITCMD',
  '25': 'IPVA',
  '26': 'Licenciamento SP, RS e MG – Pagamento com o RENAVAM',
  '27': 'DPVAT',
  '30': 'Pagamento de títulos em cobrança do próprio banco',
  '31': 'Pagamento de títulos em cobrança em outros bancos',
  '32': 'Nota fiscal – liquidação eletrônica',
  '35': 'FGTS',
  '41': 'TED – outro titular',
  '43': 'TED – mesmo titular',
  '45': 'Pix transferência',
  '47': 'Pix qr-code',
  '50': 'Débito em conta corrente – recebimento',
  '60': 'Cartão salário',
  '71': 'Pagamento de Guia de Depósito Judicial',
  '91': 'GNRE e tributos com código de barras',
  '99': 'Pagamento de Concessionárias'
}
