export default {
  '00': 'Optantes',
  '01': 'Cobrança',
  '03': 'Bloqueto Eletrônico',
  '04': 'Conciliação Bancária',
  '05': 'Débitos/recebimento',
  '06': 'Custódia de Cheques',
  '07': 'Gestão de Caixa',
  '08': 'Consulta/Informação Margem',
  '09': 'Averbação da Consignação/Retenção',
  '10': 'Pagamento dividendos',
  '11': 'Manutenção da Consignação',
  '12': 'Consignação de Parcelas',
  '13': 'Glosa da Consignação (INSS)',
  '14': 'Consulta de Tributos a Pagar DETRAN (SP, RS e MG) com RENAVAM',
  '15': 'Debêntures',
  '20': 'Pagamento fornecedor',
  '22': 'Pagamento de contas, tributos e impostos',
  '25': 'Compror',
  '26': 'Compror Rotativo',
  '29': 'Alegação do Sacado',
  '30': 'Pagamento salários',
  '32': 'Pagamento de honorários',
  '33': 'Pagamento de bolsa auxílio',
  '34': 'Pagamento de prebenda (remuneração a padres e sacerdotes)',
  '40': 'Fundos de investimentos ou vendor',
  '41': 'Vendor a Termo',
  '50': 'Pagamento sinistros segurados',
  '55': 'Consulta e Agenda Boletos de Cobrança',
  '60': 'Pagamento despesas viajante em trânsito',
  '70': 'Pagamento autorizado',
  '75': 'Pagamento credenciados',
  '77': 'Pagamento de Remuneração',
  '80': 'Pagamento representantes / vendedores autorizados',
  '90': 'Pagamento benefícios',
  '98': 'Pagamentos diversos',
  '99': 'Exclusivo Banco'
}
