export default {
  '101': 'Cheques',
  '102': 'Encargos',
  '103': 'Estornos débito',
  '104': 'Lançamentos avisados débito',
  '105': 'Tarifas',
  '106': 'Aplicação',
  '107': 'Empréstimo / financiamento débito',
  '108': 'Câmbio débito',
  '109': 'Cpmf',
  '110': 'Iof',
  '111': 'Imposto de renda',
  '112': 'Pagamento fornecedores débito',
  '113': 'Pagamento funcionários',
  '114': 'Saque eletrônico',
  '115': 'Ações débito',
  '116': 'Seguro débito',
  '117': 'Transferência entre contas débito',
  '118': 'Devolução da compensação débito',
  '119': 'Devolução de cheques débito',
  '120': 'Transferência interbancárias (doc/ted) débito',
  '121': 'Antecipação a fornecedores',
  '122': 'Oc / aerops',
  '123': 'Saque em espécie',
  '124': 'Cheque pago',
  '125': 'Pagamentos diversos débito',
  '126': 'Pagamento de tributos débito',
  '127': 'Cartão de crédito – pagamento fatura de cartão de crédito da própria if',
  '201': 'Depósitos',
  '202': 'Líquido de cobrança',
  '203': 'Devolução de cheques crédito',
  '204': 'Estornos crédito',
  '205': 'Lançamentos avisados crédito',
  '206': 'Resgate de aplicações',
  '207': 'Empréstimo / financiamento crédito',
  '208': 'Câmbio crédito',
  '209': 'Transferência interbancárias (doc/ted) crédito',
  '210': 'Ações crédito',
  '211': 'Dividendos',
  '212': 'Seguro crédito',
  '213': 'Transferência entre contas crédito',
  '214': 'Depósitos especiais',
  '215': 'Devolução de compensação crédito',
  '216': 'Oct',
  '217': 'Pagamentos fornecedores crédito',
  '218': 'Pagamentos diversos crédito',
  '219': 'Pagamentos salários',
  '220': 'Depósito em espécie',
  '221': 'Pagamento de tributos crédito',
  '222': 'Cartão de crédito – recebíveis de cartão de crédito'
}
