export default {
  '00': 'Nenhum',
  '01': 'Remessa',
  '02': 'Pedido de Baixa',
  '03': 'Pedido de Protesto Falimentar',
  '04': 'Concessão de Abatimento',
  '05': 'Cancelamento de Abatimento Concedido',
  '06': 'Alteração de Vencimento',
  '07': 'Alteração do Controle do Participante',
  '08': 'Alteração de seu Número',
  '09': 'Pedido de Protesto',
  '12': 'Ped. Exc. de Cadastro Pagador Débito',
  '13': 'Inclusão de Cadastro Pagador',
  '14': 'Alteração Cadastro Pagador',
  '18': 'Sustar Protesto e Baixar Título',
  '19': 'Sustar Protesto e Manter em Carteira',
  '20': 'Alteração de Valor*',
  '21': 'Alteração de Valor com Emissão de Boleto (quando a emissão é pelo Banco)*',
  '22': 'Transferência Cessão Crédito ID. Prod.10',
  '23': 'Transferência entre Carteiras',
  '24': 'Dev. Transferência entre Carteiras',
  '31': 'Alteração de Outros Dados',
  '32': 'Instrução de Negativação',
  '45': 'Pedido de Negativação',
  '46': 'Excluir Negativação com Baixa',
  '47': 'Excluir Negativação e Manter Pendente',
  '68': 'Acerto nos Dados do Rateio de Crédito',
  '69': 'Cancelamento do Rateio de Crédito'
}
